### ISSUE TITLE
Tailwind media queries no longer working on create-nuxt-app v3.7.1

### ISSUE THREAD

**Issue by tbredin** [nuxt/create-nuxt-app#824]
The issue is that Tailwind media queries used in PostCSS blocks in components are not compiling correctly.

To replicate, I have generated a new nuxt app with the following settings:
![image](https://user-images.githubusercontent.com/1940312/125735760-95f068c6-64cb-4e6c-8413-13289d349400.png)

To test a Tailwind media query, I have added one to the `NuxtLogo` component like so:

```vue
<style lang="postcss">
.nuxt-logo {
  height: 180px;

  @screen md {
    height: 280px;
  }
}
</style>
```

Expected CSS generated:

```css
@media (min-width: 768px)
.nuxt-logo {
    height: 280px;
}
.nuxt-logo {
    height: 180px;
}
```

Resulting CSS generated: 

```css
.nuxt-logo {
    height: 180px;
    @media (min-width: 768px) {;
    height: 280px;
    }: ;
}
```
Chrome dev tools screenshot:
![image](https://user-images.githubusercontent.com/1940312/125736085-982839a9-438f-470f-b5b3-f95b42b42659.png)

If anyone has a quick fix or workaround for me while a fix is rolled out in `create-nuxt-app` I would be eternally grateful too...
